#pragma once

#define ID_TEX_MAP			0
#define ID_TEX_MAP_3A		1
#define ID_TEX_SOPHIA		2
#define ID_TEX_SOPHIA_LOOKUP_LOW 3

#define OBJECT_TYPE_JASON	0

#define ID_SPRITE_SOPHIA_HIGH			1
#define ID_SPRITE_SOPHIA_MED				11
#define ID_SPRITE_SOPHIA_LOW				21
#define ID_SPRITE_SOPHIA_HIGH_ROT	31
#define ID_SPRITE_SOPHIA_MED_ROT	41
#define ID_SPRITE_SOPHIA_JUMP			51
#define ID_SPRITE_SOPHIA_JUMP_ROT	61
#define ID_SPRITE_SOPHIA_HIGH_DIA	71
#define ID_SPRITE_SOPHIA_HIGHER_DIA	81
#define ID_SPRITE_SOPHIA_HIGHEST_DIA 91
#define ID_SPRITE_SOPHIA_LOOK_UP	101
#define ID_SPRITE_SOPHIA_LOOK_UP_LOW 111

// FOR HIT SPRITE: ID*-1

#define ID_ANI_SOHPIA_LOOK_LEFT		1
#define ID_ANI_SOPHIA_LOOK_RIGHT	2